const express=require("express");
const authrouter=express.Router();
const authcontroller=require("../controller/authcontroller.js");
const authMiddleware=require("../middleware/auth.js");
authrouter.post("/signup",authcontroller.signup);
authrouter.post("/verify-otp",authcontroller.verifySignupOtp);
authrouter.post("/resend-otp",authcontroller.resendSignupOtp);
authrouter.post("/forgot-password",authcontroller.forgotPassword);
authrouter.post("/reset-password",authcontroller.resetPassword);
authrouter.post("/login",authcontroller.login);
authrouter.get("/me",authMiddleware,authcontroller.getme);
module.exports=authrouter;